"""empty message

Revision ID: 0f3e444d7c52
Revises: 1b5ec94a3221
Create Date: 2022-07-04 15:11:53.289917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3e444d7c52'
down_revision = '1b5ec94a3221'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('fixed_deposit', sa.Column('last_update', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_deposit', 'last_update')
    # ### end Alembic commands ###
