"""empty message

Revision ID: 10f72a732463
Revises: 2e3bd0076f9e
Create Date: 2022-07-03 22:12:47.257945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f72a732463'
down_revision = '2e3bd0076f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_deposit', sa.Column('fd_duration', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_deposit', 'fd_duration')
    # ### end Alembic commands ###
