"""empty message

Revision ID: 1b5ec94a3221
Revises: 10f72a732463
Create Date: 2022-07-03 22:14:51.866594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5ec94a3221'
down_revision = '10f72a732463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixed_deposit', sa.Column('fd_create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixed_deposit', 'fd_create_date')
    # ### end Alembic commands ###
