"""empty message

Revision ID: 2d6af6d9d9ef
Revises: 5cf4521c3091
Create Date: 2022-06-23 15:43:45.054258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6af6d9d9ef'
down_revision = '5cf4521c3091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_branch_id_fkey', 'account', type_='foreignkey')
    op.drop_constraint('account_user_id_fkey', 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'account', 'branch', ['branch_id'], ['branch_id'], ondelete='CASCADE')
    op.drop_constraint('account_type_account_number_fkey', 'account_type', type_='foreignkey')
    op.create_foreign_key(None, 'account_type', 'account', ['account_number'], ['account_number'], ondelete='CASCADE')
    op.drop_constraint('atm_bank_id_fkey', 'atm', type_='foreignkey')
    op.create_foreign_key(None, 'atm', 'bank_details', ['bank_id'], ['bank_id'], ondelete='CASCADE')
    op.drop_constraint('branch_bank_id_fkey', 'branch', type_='foreignkey')
    op.create_foreign_key(None, 'branch', 'bank_details', ['bank_id'], ['bank_id'], ondelete='CASCADE')
    op.drop_constraint('card_account_number_fkey', 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'account', ['account_number'], ['account_number'], ondelete='CASCADE')
    op.drop_constraint('fixed_deposit_account_number_fkey', 'fixed_deposit', type_='foreignkey')
    op.create_foreign_key(None, 'fixed_deposit', 'account', ['account_number'], ['account_number'], ondelete='CASCADE')
    op.drop_constraint('insurance_user_id_fkey', 'insurance', type_='foreignkey')
    op.create_foreign_key(None, 'insurance', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('insurance_type_insurance_id_fkey', 'insurance_type', type_='foreignkey')
    op.create_foreign_key(None, 'insurance_type', 'insurance', ['insurance_id'], ['insurance_id'], ondelete='CASCADE')
    op.drop_constraint('loan_type_loan_id_fkey', 'loan_type', type_='foreignkey')
    op.create_foreign_key(None, 'loan_type', 'loan', ['loan_id'], ['loan_id'], ondelete='CASCADE')
    op.drop_constraint('transaction_user_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('transaction_type_transaction_id_fkey', 'transaction_type', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_type', 'transaction', ['transaction_id'], ['transaction_id'], ondelete='CASCADE')
    op.drop_constraint('user_type_user_id_fkey', 'user_type', type_='foreignkey')
    op.create_foreign_key(None, 'user_type', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_type', type_='foreignkey')
    op.create_foreign_key('user_type_user_id_fkey', 'user_type', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'transaction_type', type_='foreignkey')
    op.create_foreign_key('transaction_type_transaction_id_fkey', 'transaction_type', 'transaction', ['transaction_id'], ['transaction_id'])
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_user_id_fkey', 'transaction', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'loan_type', type_='foreignkey')
    op.create_foreign_key('loan_type_loan_id_fkey', 'loan_type', 'loan', ['loan_id'], ['loan_id'])
    op.drop_constraint(None, 'insurance_type', type_='foreignkey')
    op.create_foreign_key('insurance_type_insurance_id_fkey', 'insurance_type', 'insurance', ['insurance_id'], ['insurance_id'])
    op.drop_constraint(None, 'insurance', type_='foreignkey')
    op.create_foreign_key('insurance_user_id_fkey', 'insurance', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'fixed_deposit', type_='foreignkey')
    op.create_foreign_key('fixed_deposit_account_number_fkey', 'fixed_deposit', 'account', ['account_number'], ['account_number'])
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key('card_account_number_fkey', 'card', 'account', ['account_number'], ['account_number'])
    op.drop_constraint(None, 'branch', type_='foreignkey')
    op.create_foreign_key('branch_bank_id_fkey', 'branch', 'bank_details', ['bank_id'], ['bank_id'])
    op.drop_constraint(None, 'atm', type_='foreignkey')
    op.create_foreign_key('atm_bank_id_fkey', 'atm', 'bank_details', ['bank_id'], ['bank_id'])
    op.drop_constraint(None, 'account_type', type_='foreignkey')
    op.create_foreign_key('account_type_account_number_fkey', 'account_type', 'account', ['account_number'], ['account_number'])
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key('account_user_id_fkey', 'account', 'user', ['user_id'], ['user_id'])
    op.create_foreign_key('account_branch_id_fkey', 'account', 'branch', ['branch_id'], ['branch_id'])
    # ### end Alembic commands ###
