"""empty message

Revision ID: 51a1d44627c6
Revises: 0f3e444d7c52
Create Date: 2022-07-06 10:32:04.263475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a1d44627c6'
down_revision = '0f3e444d7c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurance_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_role')
    op.drop_table('loan_details')
    op.drop_table('insurance_details')
    # ### end Alembic commands ###
