"""empty message

Revision ID: 5cf4521c3091
Revises: 563d12afccb5
Create Date: 2022-06-23 15:41:08.767841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf4521c3091'
down_revision = '563d12afccb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('loan_user_id_fkey', 'loan', type_='foreignkey')
    op.create_foreign_key(None, 'loan', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.create_foreign_key('loan_user_id_fkey', 'loan', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
